#!/usr/bin/env python3
"""Build a self-hosted Font Awesome subset containing only the icons the site uses.

The full Font Awesome CDN bundle is ~290 KB (CSS + solid + brands fonts) for
the few dozen icons this site actually shows. This scans the HTML/JS for
`fa-<name>` classes and writes:

    assets/fa/fa.css               base rules + @font-face + used icon rules
    assets/fa/fa-solid-900.woff2   subset to the used solid glyphs
    assets/fa/fa-brands-400.woff2  subset to the used brand glyphs

Re-run it whenever you add an icon:

    npm pack @fortawesome/fontawesome-free@6.5.0 && tar xzf fortawesome-*.tgz
    pip install fonttools brotli
    python3 scripts/build_icons.py path/to/package
"""
import pathlib
import re
import sys

from fontTools import subset
from fontTools.ttLib import TTFont

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "assets" / "fa"
SCAN_GLOBS = ["*.html", "blog/*.html", "case-studies/*.html", "assets/*.js"]

BASE_CSS = """/* Font Awesome Free 6.5.0 subset — https://fontawesome.com/license/free
   (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT). Generated by
   scripts/build_icons.py — do not edit by hand. */
@font-face{font-family:'Font Awesome 6 Free';font-style:normal;font-weight:900;font-display:block;src:url(fa-solid-900.woff2) format("woff2")}
@font-face{font-family:'Font Awesome 6 Brands';font-style:normal;font-weight:400;font-display:block;src:url(fa-brands-400.woff2) format("woff2")}
.fa,.fas,.fa-solid,.fab,.fa-brands{-moz-osx-font-smoothing:grayscale;-webkit-font-smoothing:antialiased;display:var(--fa-display,inline-block);font-style:normal;font-variant:normal;line-height:1;text-rendering:auto}
.fa,.fas,.fa-solid{font-family:'Font Awesome 6 Free';font-weight:900}
.fab,.fa-brands{font-family:'Font Awesome 6 Brands';font-weight:400}
"""


def used_icon_names():
    names = set()
    for pattern in SCAN_GLOBS:
        for path in ROOT.glob(pattern):
            names.update(re.findall(r"\bfa-([a-z0-9]+(?:-[a-z0-9]+)*)", path.read_text()))
    return names


def icon_codepoints(css):
    """Map icon name -> codepoint from the package's css/all.css."""
    mapping = {}
    for selectors, cp in re.findall(r"([^{}]+)\{\s*content:\s*\"\\([0-9a-f]+)\";\s*\}", css):
        for name in re.findall(r"\.fa-([a-z0-9-]+)::?before", selectors):
            mapping[name] = int(cp, 16)
    return mapping


def subset_font(src, dst, codepoints):
    font = TTFont(src)
    cmap = font.getBestCmap()
    keep = sorted(cp for cp in codepoints if cp in cmap)
    opts = subset.Options()
    opts.flavor = "woff2"
    opts.layout_features = []
    opts.name_IDs = []
    opts.notdef_outline = True
    sub = subset.Subsetter(opts)
    sub.populate(unicodes=keep)
    sub.subset(font)
    font.flavor = "woff2"
    font.save(dst)
    return set(keep)


def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    pkg = pathlib.Path(sys.argv[1])
    mapping = icon_codepoints((pkg / "css" / "all.css").read_text())
    names = sorted(n for n in used_icon_names() if n in mapping)
    cps = {mapping[n] for n in names}

    OUT.mkdir(parents=True, exist_ok=True)
    got = subset_font(pkg / "webfonts" / "fa-solid-900.ttf", OUT / "fa-solid-900.woff2", cps)
    got |= subset_font(pkg / "webfonts" / "fa-brands-400.ttf", OUT / "fa-brands-400.woff2", cps)
    missing = [n for n in names if mapping[n] not in got]
    if missing:
        sys.exit(f"no glyph in solid/brands fonts for: {', '.join(missing)}")

    rules = "".join(f'.fa-{n}:before{{content:"\\{mapping[n]:x}"}}\n' for n in names)
    (OUT / "fa.css").write_text(BASE_CSS + rules)
    print(f"{len(names)} icons -> {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
